[package]
name = "spotifly-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "spotifly_rust"
crate-type = ["staticlib"]

[dependencies]
librespot-oauth = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
once_cell = "1.19"

[profile.release]
opt-level = 3
lto = true
